version: '1.0'
services:
  postgres:
    image: postgres:16-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s